### ISSUE TITLE
Social module

### ISSUE THREAD

**Issue by arthtyagi** [DevClad-Inc/devclad#44]
Functionality for:
- [x] Weekly 1:1 match (using KNN to find the match) DevClad-Inc/devclad-server#11 
- [x] DevClad-Inc/devclad-server#13
- [x] DevClad-Inc/devclad#48

1:1 match: Chat | if video_call_frinedly → “Hey, when are you free to have a video chat?"
